const movieData = {
  page: 1,
  results: [
    {
      backdrop_path: "/uGmYqxh8flqkudioyFtD7IJSHxK.jpg",
      id: 889737,
      title: "Joker: Folie à Deux",
      original_title: "Joker: Folie à Deux",
      overview:
        "While struggling with his dual identity, Arthur Fleck not only stumbles upon true love, but also finds the music that's always been inside him.",
      poster_path: "/aciP8Km0waTLXEYf5ybFK5CSUxl.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [18, 80, 53],
      popularity: 771.741,
      release_date: "2024-10-01",
      video: false,
      vote_average: 5.7,
      vote_count: 987,
    },
    {
      backdrop_path: "/3V4kLQg0kSqPLctI5ziYWabAZYF.jpg",
      id: 912649,
      title: "Venom: The Last Dance",
      original_title: "Venom: The Last Dance",
      overview:
        "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
      poster_path: "/k42Owka8v91trK1qMYwCQCNwJKr.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [878, 28, 12],
      popularity: 7087.676,
      release_date: "2024-10-22",
      video: false,
      vote_average: 6.6,
      vote_count: 270,
    },
    {
      backdrop_path: "/xlkclSE4aq7r3JsFIJRgs21zUew.jpg",
      id: 1034541,
      title: "Terrifier 3",
      original_title: "Terrifier 3",
      overview:
        "Five years after surviving Art the Clown's Halloween massacre, Sienna and Jonathan are still struggling to rebuild their shattered lives. As the holiday season approaches, they try to embrace the Christmas spirit and leave the horrors of the past behind. But just when they think they're safe, Art returns, determined to turn their holiday cheer into a new nightmare. The festive season quickly unravels as Art unleashes his twisted brand of terror, proving that no holiday is safe.",
      poster_path: "/63xYQj1BwRFielxsBDXvHIJyXVm.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 53],
      popularity: 4379.543,
      release_date: "2024-10-09",
      video: false,
      vote_average: 7.3,
      vote_count: 287,
    },
    {
      backdrop_path: "/oqWTbBixgF8XwqzGeFWMzkNwqAw.jpg",
      id: 1236419,
      title: "Piece by Piece",
      original_title: "Piece by Piece",
      overview:
        "The story of the life and career of American musician Pharrell Williams in the style of LEGO animation.",
      poster_path: "/9xSjP8B0iZHRzvrtKcYDkaalomS.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 10402, 99],
      popularity: 28.711,
      release_date: "2024-10-10",
      video: false,
      vote_average: 8.4,
      vote_count: 13,
    },
    {
      backdrop_path: "/9oYdz5gDoIl8h67e3ccv3OHtmm2.jpg",
      id: 933260,
      title: "The Substance",
      original_title: "The Substance",
      overview:
        "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
      poster_path: "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 878, 53],
      popularity: 2500.142,
      release_date: "2024-09-07",
      video: false,
      vote_average: 7.272,
      vote_count: 1001,
    },
    {
      backdrop_path: "/3Udwq6W7y4AIsuJDXV2YwowZ1gQ.jpg",
      id: 113962,
      name: "Lioness",
      original_name: "Lioness",
      overview:
        "Cruz Manuelos, a rough-around-the-edges but passionate young Marine, is recruited to join the CIA's Lioness Engagement Team to help bring down a terrorist organization from within. Joe, the station chief of the Lioness program, is tasked with training, managing and leading her female undercover operatives.",
      poster_path: "/ajaXSmdAlYYhnvx1EIsvpfN949y.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [18, 10768],
      popularity: 519.719,
      first_air_date: "2023-07-23",
      vote_average: 8,
      vote_count: 659,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/oPUOpnl3pqD8wuidjfUn17mO1yA.jpg",
      id: 698687,
      title: "Transformers One",
      original_title: "Transformers One",
      overview:
        "The untold origin story of Optimus Prime and Megatron, better known as sworn enemies, but once were friends bonded like brothers who changed the fate of Cybertron forever.",
      poster_path: "/iHPIBzrjJHbXeY9y7VVbEVNt7LW.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 878, 12, 10751, 28],
      popularity: 4381.997,
      release_date: "2024-09-11",
      video: false,
      vote_average: 8.1,
      vote_count: 420,
    },
    {
      backdrop_path: "/2K2iXKB5sDJ0V3Q6U6VBmuzCPXl.jpg",
      id: 1063877,
      title: "Don't Move",
      original_title: "Don't Move",
      overview:
        "A grieving woman in a secluded forest encounters a killer who injects her with a paralytic drug. As her body shuts down, her fight for survival begins.",
      poster_path: "/cRDJxdnRb7ikKd6fVJTrGeaL34v.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 53],
      popularity: 222.216,
      release_date: "2024-10-24",
      video: false,
      vote_average: 6.704,
      vote_count: 218,
    },
    {
      backdrop_path: "/begseNUKhZcc05Bc1UggaX5GeES.jpg",
      id: 976734,
      title: "Canary Black",
      original_title: "Canary Black",
      overview:
        "Top level CIA agent Avery Graves is blackmailed by terrorists into betraying her own country to save her kidnapped husband. Cut off from her team, she turns to her underworld contacts to survive and help locate the coveted intelligence that the kidnappers want.",
      poster_path: "/hhiR6uUbTYYvKoACkdAIQPS5c6f.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 53, 80],
      popularity: 186.924,
      release_date: "2024-10-10",
      video: false,
      vote_average: 6.7,
      vote_count: 119,
    },
    {
      backdrop_path: "/VSRmtRlYgd0pBISf7d34TAwWgB.jpg",
      id: 194764,
      name: "The Penguin",
      original_name: "The Penguin",
      overview:
        'Follow Oswald "Oz" Cobb’s quest for control in Gotham City. With the city in peril following the seawall\'s collapse, Oz seeks to fill the power vacuum left by the death of Carmine Falcone and finally give his mother Francis the life he\'s always promised. But first, Oz must confront his enemies and his own demoralizing reputation as "the Penguin."',
      poster_path: "/a2fqompEWB2GFp9GOdlqLcfEFfw.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [18, 80],
      popularity: 1084.436,
      first_air_date: "2024-09-19",
      vote_average: 8.4,
      vote_count: 249,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/1Oi7u3ebJbz9glmG4GV0rEZmICC.jpg",
      id: 1184918,
      title: "The Wild Robot",
      original_title: "The Wild Robot",
      overview:
        "After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island's animals and cares for an orphaned baby goose.",
      poster_path: "/wTnV3PCVW5O92JMrFvvrRcV39RU.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [16, 878, 10751],
      popularity: 6494.003,
      release_date: "2024-09-12",
      video: false,
      vote_average: 8.587,
      vote_count: 1922,
    },
    {
      backdrop_path: "/gZWl93sf8AxavYpVT1Un6EF3oCj.jpg",
      id: 475557,
      title: "Joker",
      original_title: "Joker",
      overview:
        "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
      poster_path: "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [80, 53, 18],
      popularity: 257.728,
      release_date: "2019-10-01",
      video: false,
      vote_average: 8.2,
      vote_count: 25537,
    },
    {
      backdrop_path: "/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
      id: 533535,
      title: "Deadpool & Wolverine",
      original_title: "Deadpool & Wolverine",
      overview:
        "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
      poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [28, 35, 878],
      popularity: 2031.043,
      release_date: "2024-07-24",
      video: false,
      vote_average: 7.7,
      vote_count: 4875,
    },
    {
      backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17rUaC.jpg",
      id: 945961,
      title: "Alien: Romulus",
      original_title: "Alien: Romulus",
      overview:
        "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
      poster_path: "/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [878, 27],
      popularity: 3030.239,
      release_date: "2024-08-13",
      video: false,
      vote_average: 7.3,
      vote_count: 1985,
    },
    {
      backdrop_path: "/fzkLKtZCkYSDzxoqntE5KgIqvzk.jpg",
      id: 1084736,
      title: "The Count of Monte-Cristo",
      original_title: "Le Comte de Monte-Cristo",
      overview:
        "Edmond Dantes becomes the target of a sinister plot and is arrested on his wedding day for a crime he did not commit. After 14 years in the island prison of Château d’If, he manages a daring escape. Now rich beyond his dreams, he assumes the identity of the Count of Monte-Cristo and exacts his revenge on the three men who betrayed him.",
      poster_path: "/sAT1P3FGhtJ68anUyJScnMu8t1l.jpg",
      media_type: "movie",
      adult: false,
      original_language: "fr",
      genre_ids: [12, 36, 28, 18, 10749, 53],
      popularity: 313.496,
      release_date: "2024-06-28",
      video: false,
      vote_average: 8.383,
      vote_count: 672,
    },
    {
      backdrop_path: "/vohINT54Cvez6xu2LyGTHYjUe28.jpg",
      id: 1320637,
      title: "Am I Racist?",
      original_title: "Am I Racist?",
      overview:
        "Matt Walsh goes deep undercover in the world of diversity, equity, and inclusion. Prepare to be shocked by how far race hustlers will go and how much further Matt Walsh will go to expose the grift, uncovering absurdities that will leave you laughing.",
      poster_path: "/yK8jErx0a0P6QpsyuFkeZr2Rn9a.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [35, 99],
      popularity: 34.842,
      release_date: "2024-09-13",
      video: false,
      vote_average: 6.8,
      vote_count: 21,
    },
    {
      backdrop_path: "/q3UGWifvIpdey1T2efX4dSmbZpU.jpg",
      id: 124364,
      name: "FROM",
      original_name: "FROM",
      overview:
        "Unravel the mystery of a nightmarish town in middle America that traps all those who enter. As the unwilling residents fight to keep a sense of normalcy and search for a way out, they must also survive the threats of the surrounding forest – including the terrifying creatures that come out when the sun goes down.",
      poster_path: "/cjXLrg4R7FRPFafvuQ3SSznQOd9.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [9648, 18, 10765],
      popularity: 2319.256,
      first_air_date: "2022-02-20",
      vote_average: 8.174,
      vote_count: 1327,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/oyZWiPvumwSYMrF2XbZH6yXQZ14.jpg",
      id: 107113,
      name: "Only Murders in the Building",
      original_name: "Only Murders in the Building",
      overview:
        "Three strangers share an obsession with true crime and suddenly find themselves wrapped up in one.",
      poster_path: "/bZubW4eLAk2zqk44fSWRDTFfcba.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [35, 9648, 80],
      popularity: 301.287,
      first_air_date: "2021-08-31",
      vote_average: 8.3,
      vote_count: 1418,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/ymTx7ebsmBjqh47fiZnBUjIDx5K.jpg",
      id: 138501,
      name: "Agatha All Along",
      original_name: "Agatha All Along",
      overview:
        "Agatha Harkness gathers a coven of witches and sets off down, down, down The Witches' Road.",
      poster_path: "/1tfCj5h0FEQ5xg8hzVjQgcuGlgN.jpg",
      media_type: "tv",
      adult: false,
      original_language: "en",
      genre_ids: [10765, 9648],
      popularity: 885.988,
      first_air_date: "2024-09-18",
      vote_average: 7.7,
      vote_count: 330,
      origin_country: ["US"],
    },
    {
      backdrop_path: "/cVg97LOJgrDZJ7bVmjU2KsGRYnU.jpg",
      id: 1100782,
      title: "Smile 2",
      original_title: "Smile 2",
      overview:
        "About to embark on a new world tour, global pop sensation Skye Riley begins experiencing increasingly terrifying and inexplicable events. Overwhelmed by the escalating horrors and the pressures of fame, Skye is forced to face her dark past to regain control of her life before it spirals out of control.",
      poster_path: "/aE85MnPIsSoSs3978Noo16BRsKN.jpg",
      media_type: "movie",
      adult: false,
      original_language: "en",
      genre_ids: [27, 9648],
      popularity: 630.746,
      release_date: "2024-10-16",
      video: false,
      vote_average: 6.889,
      vote_count: 212,
    },
  ],
  total_pages: 500,
  total_results: 10000,
};

export { movieData };
